### ISSUE TITLE
Feature request: Add replace window option. 

### ISSUE THREAD

**Issue by onodera-punpun** [phillipberndt/pqiv#44]
Like pho: https://github.com/akkana/pho/blob/346421aa1a6d09e03faeddb0103e9657c80fc994/gwin.c#L20 & https://github.com/akkana/pho/blob/346421aa1a6d09e03faeddb0103e9657c80fc994/doc/pho.1#L40

**Comment by phillipberndt** [comment]
I'd prefer to try to fix bugs with WMs directly before using such a drastic approach. Which issues do you experience, and with which WM?

**Comment by onodera-punpun** [comment]
I'm using openbox & fvwm.

This is kinda hard to explain, especially since English is my second language but I'll try: I want this options because I don't use the center window option of pqiv, but when loading multiple images I want the center of the window to stay the same (however the center of the window doesn't have to be center of the monitor!).

in both openbox and fvwm I've set an option that makes new windows spawn under the cursor. By combining this with a replace-window option the windows jump around way less.

I created a webm that hopefully explains this a bit better: https://sr.ht/fOOp.webm

The first image viewer is pqiv, like you can see the image jumps around a lot, the second one is pho.

**Comment by phillipberndt** [comment]
You can use `--window-position=off` to switch off positioning. That's not quite what you want - it will (probably) leave the upper left corner in place instead of the window's center. Combined with

    gtk_window_set_gravity(main_window, GDK_GRAVITY_CENTER);

somewhere in `create_window`, around line 3950, this should what you want?! (This line will have some unexpected side effects though, I'll probably have to work around some bugs. That said, resizing around the window's center does indeed feel much better, I'm tempted to make this the default behaviour.)

**Comment by phillipberndt** [comment]
See my latest upload. Is this an improvement?

**Comment by onodera-punpun** [comment]
It's better but not perfect yet, Example:

https://sr.ht/pikY.png jumps too https://sr.ht/Agpr.png

The two pictures in question: https://sr.ht/oxgN.jpg https://sr.ht/m6MB.jpg

**Comment by phillipberndt** [comment]
Too bad.. in Cinnamon, this works as expected with your images. I thought about reimplementing the whole resizing/positioning on my own for a while now, because there are indeed many incompatibilities and rough edges in general between the different WMs and GDKs code for handling it. I'll look into this soon.

In the meantime, in `image_loaded_handler`, near line 1442, directly above the line that calls `set_scale_level_for_screen`, insert

	if(!main_window_in_fullscreen) {
		gtk_widget_unmap(GTK_WIDGET(main_window));
		gtk_widget_map(GTK_WIDGET(main_window));
	}

This should close & reopen the window whenever a new image is loaded. Combined with `--window-position=off` this should work as expected.

**Comment by onodera-punpun** [comment]
The unmap/map thing didn't really work, I think the window actually needs to be destroyed in order for it to work. Anyways I've been experimenting with a "follow cursor position option", keep in mind I don't know anything about programming :p 

```
	if(!main_window_in_fullscreen) {
		gint cursor_x = -1;
		gint cursor_y = -1;
		gint window_w = -1;
		gint window_h = -1;

		gdk_window_get_pointer(NULL, &cursor_x, &cursor_y, NULL);
		gtk_window_get_size(main_window, &window_w, &window_h);

		gtk_window_move(main_window, cursor_x - window_w / 2, cursor_y - window_h / 2);
	}
```

This works great when all images are the exact same size, however the pqiv window still jumps when the image size differs.

**Comment by phillipberndt** [comment]
Lacking a working better solution, I now added `--recreate-window` in the `recreate-window` branch. Does this work as expected, and do you still need the feature?

**Comment by onodera-punpun** [comment]
Works perfectly, thanks!
