### ISSUE TITLE
Delayed Zoom

### ISSUE THREAD

**Issue by noctuid** [phillipberndt/pqiv#48]
Zooming works fine on animated images, but when I try to zoom on a normal image, nothing happens until I take some wm action like switching desktops (after which it will redisplay with zoom). I'm using bspwm, but I haven't noticed anything like this happen for other programs. Any ideas about what might be causing this?

**Comment by phillipberndt** [comment]
Thanks for reporting this, I'll look into it. Does it work as expected in fullscreen?

**Comment by noctuid** [comment]
Yes, it does actually work in fullscreen.

**Comment by phillipberndt** [comment]
I've added a check that tests if the WM announces `_NET_MOVERESIZE_WINDOW` in an attempt to recognize tiling WMs and explicitly redraw upon zoom. Does this fix this issue?! (I'm wondering because e.g. i3 did not have this issue, so apparently gtk already did issue a redraw request somewhere along the way..)

**Comment by phillipberndt** [comment]
Also, could you please paste the output of `xprop _NET_WM_ALLOWED_ACTIONS` both for a tiled window and (if bspwm supports them) a floating one? I'm curious if bspwm properly announces that it does not support `_NET_WM_ACTION_RESIZE`

**Comment by noctuid** [comment]
Yes, the problem is fixed with the latest commits. Bspwm gives no information for `_NET_WM_ALLOWED_ACTIONS` (I get "not found" for both floating and tiling windows).
