### ISSUE TITLE
Inconsistent Left Click / Spacebar operation

### ISSUE THREAD

**Issue by johnivey** [phillipberndt/pqiv#52]
Whenever I left or right click to change images, it skips every other file, or at least it appears that way, I only have four files in the directory.  If I hit the spacebar, it cycles through all the images as expected.

**Comment by phillipberndt** [comment]
The left button goes to the previous image, the right one to the next. (This is ill-documented, I just fixed that.) When the work on the [actions branch](https://github.com/phillipberndt/pqiv/tree/actions) is completed, you'll be able to change pqiv's behaviour.

This would explain your issue if you only had three files. But your issue is that with the images numbered 1-4, starting from image 1, both the left and right mouse button take you to number 3, skipping 2 and 4, respectively, right?
