### ISSUE TITLE
Questions about 

### ISSUE THREAD

**Issue by hetraeus** [phillipberndt/pqiv#65]
### 1

I cannot find a way to change the window and the alpha channel colors. The man page does not mention "color". Is it even possible?
### 2

`command-1=|pinta`
`command-2=|gimp`

or 

`command-1=pinta`
`command-2=gimp`

issue command 1 or 2 -> crash. Am I doing it wrong? Well at least it should not crash.
strace relevant lines must be:
`20:20:13 recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"#\203_\1\26\0\0\0\2\0\3\0\356\216\236\0\v\0\0\0\230\4\0\0\4\0@\2\0\0\0\0"..., 4096}], msg_controllen=0, msg_flags=0}, 0) = 120
20:20:13 recvmsg(3, 0x7ffe4ab25ec0, 0)  = -1 EAGAIN (Resource temporarily unavailable)
20:20:13 --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x7fad3173e053} ---
20:20:13 +++ killed by SIGSEGV (core dumped) +++
zsh: segmentation fault (core dumped)  strace -t pqiv shot0034.jpg`

pqiv is compiled with support for everything, libav included.
### 3

Zoom in/out seems to be ignored most of the times. The commands in my .pqivrc are:
`<Control><Mouse-Scroll-1>  { set_scale_level_relative(1.1)      }`
`<Control><Mouse-Scroll-2>  { set_scale_level_relative(0.9)      }`
### 4

Probably minor, clang throws few complains while compiling.

I am writing everything here to avoid littering the bug list.

**Comment by phillipberndt** [comment]
1) I'm not sure whether I understand the question. Do you search for a way to change the black background and/or the colors of the checkerboard pattern for transparent images? This isn't possible right now, feel free to add this though - the colors are currently hard-coded, you'd have to replace them with a value from the command line (using a long option, please! I try not to waste short options on special features.)

2) Neither variant should crash, and none does here. The recvmsg comes from glib, there's nothing wrong there. Could you please produce a backtrace? (That is, run `gdb --args pqiv --command-1="|gimp" foo...` using a freshly compiled version of pqiv, with debug symbols still in place, and then upon the crash type `bt` in the gdb prompt and paste the output)

3) Works for me. Does `xev` recognize the input? I see the events as `ButtonPress`/`ButtonRelease` sequences with `state 0x14, button 4` and `button 5`, respectively.

4) Do you mean the warning that `break` will never be executed? If yes, then that's intentional. There are other compilers which complain if the `break`s aren't in place, and frankly, I find clang's behaviour weird here. A `break` inside a `select` that isn't executed due to a `return` just above, without any code in between, shouldn't trigger this warning, because there can't possibly be any side effects.
