### ISSUE TITLE
Make cursor invisible after delay

### ISSUE THREAD

**Issue by noctuid** [phillipberndt/pqiv#72]
One thing I like about mpv is that the cursor will turn invisible over the image/video after a short delay. Currently you can make the cursor always visible or always invisible, but could it also be possible to make the cursor invisible after a short delay? I like this feature because you can see the cursor again after moving it, so you'll know where it is again automatically.

**Comment by phillipberndt** [comment]
This is in master now. I really like the idea, but haven't made it the default behaviour, because it requires pqiv to ask X11 for pointer events - right now it only receives those if simultaneously a mouse button is pressed. This results in quite some communication overhead, which will probably become noticeable at least in remote sessions (through SSH). You can activate this using `--action="set_cursor_auto_hide(1)"`.

**Comment by noctuid** [comment]
Thanks! It works well. Could there be an option/flag for it, so I could set the behavior in the config file (`action=...` in the config file doesn't seem to be supported)?

**Comment by phillipberndt** [comment]
That was a bug which should be resolved now. I've also added supported for an `[actions]` section, that is, you can write

    [action]
    set_cursor_auto_hide(1)

in your pqivrc now.

**Comment by noctuid** [comment]
Very nice! Thank you.
