### ISSUE TITLE
Lack of pqiv.desktop file being installed on make install

### ISSUE THREAD

**Issue by jgkamat** [phillipberndt/pqiv#73]
Most (at least gui) applications provide a *.desktop file, which lets the system know what types of files that application can open. This is used, for example, in many desktop environments for choosing which application to launch (as it contains information about which files this application can open). I personally use the `xdg-open` command, which uses these desktop files, along with a small file to pick which application I set as default to open the selected file.

Unfortunately pqiv does not have this yet, and I would really appreciate it if one could be added!

It's not too hard to write one of these, and I would be happy to create a simple one if you're feeling busy :smile:.

Here is feh's example desktop file: https://github.com/derf/feh/blob/master/share/applications/feh.pre (which is dynamically generated based off what it was configured with)

Here is mpv's desktop file: https://github.com/mpv-player/mpv/blob/master/etc/mpv.desktop

Let me kow what you think!

**Comment by phillipberndt** [comment]
I've played around with this, here's what I've found so far:

Regarding automated generation of a list of MIME types:

1. GTK prior to version 3.22 (Ubuntu stable has 3.18) has *no API whatsoever* to extract mime types from an already created `GtkFileFilter`. Adding an option to pqiv that outputs a list of supported MIME types would hence be a lot of overhead.
2. Creating a second binary with the sole purpose of creating such a list would be another option, but it'd suffer from the same problem: Since the backends currently only create a `GtkFileFilter`, I'd have to add another function to each backend; one which returns a list of mime types
3. Some backends have external programs that output a list of MIME types: There are `gdk-pixbuf-query-loaders` and `convert -list mime`.
4. A static list would be an option, see 2734c98dd46c in the desktop-entry branch.

But

5. Installing the desktop file does not suffice. One also has to execute `update-desktop-database` afterwards, or the MIME cache file in the `share/applications` directory won't be updated.

The last point makes me have serious doubts on whether this is a good idea. In my opinion, `make install` should never assume that it is *actually* installing the application on the system - in many cases, it is only called to prepare the directory structure for a packaging script of a specific distribution. On the other hand, if I'd start installing the desktop file without calling `update-desktop-database`, users manually installing pqiv would start wondering why pqiv doesn't show up in their "Execute with" lists.

Also, some systems have their own version of this mechanism, though I admit that this it is in retreat in the Linux world. For example, Debian has `/usr/lib/mime/packages/`. Microsoft Windows has the information somewhere in the registry.

I'll have to think about a good solution, and maybe check how others resolve this problem. Suggestions are welcome! In any case, I could include a desktop file in the code tree without automatically installing it, if that'd suffice for you?!

**Comment by jgkamat** [comment]
Wow, thanks for the fast reply!

I was honestly expecting a static desktop entry with common image mimetypes, but this solution is great, although it would need to be maintained if more backends are added. 

As far as I can tell (and I could be wrong), the convention is to put desktop files into place without updating the mime database. (looking at feh, mpv, and keepassx). In the end, if distribution's packaging scripts copy the file over into the applications directory, it dosen't matter too much for end users, as most people are installing packaged versions. I would still support copying the desktop file over though, as for users manually installing pqiv, update-mime-database will eventually run (when the user installs something from their package manager), and the entry will appear (and as far as I know, `xdg-open` dosen't use the mime database). Most people who are installing pqiv manually (I think) would know that the mime database is updated, as there are many other applications that follow the same structure.

In the end, I don't mind about whether the desktop file is copied over during `make install` or not, but I do care if it's in place when it's packaged by various distributions. I have no idea how this works, but I would think that including the desktop file in `make install` would signal maintainers to add the desktop file per distribution rules (but I'm not sure if thats how that works). 

Thanks for doing this though, it looks great! :smile:

**Comment by phillipberndt** [comment]
Indeed the various package managers all seem to have mechanisms in place to detect installed desktop files and trigger a run of `update-desktop-database` on their own. I went through and pulled the change to master; maybe I'll come up with a better mechanism for creating the list of MIME types in the future, but for now, this one should suffice.
