### ISSUE TITLE
Add support to opening images from webpages/network

### ISSUE THREAD

**Issue by anonish** [phillipberndt/pqiv#86]
Is it possible to add support to opening images from a webpage?

If I run:

pqiv http://static4.businessinsider.com/image/56c640526e97c625048b822a-480/donald-trump.jpg

I get:

Failed to load image http://static4.businessinsider.com/image/56c640526e97c625048b822a-480/donald-trump.jpg: Operation not supported

this happen with all links to images (direct link to the image)

as an example, if I run the same with feh:
feh  http://static4.businessinsider.com/image/56c640526e97c625048b822a-480/donald-trump.jpg

the image pops up directly with no errors.

would this be possible? I prefer pqiv over feh due to faster handling of directories with large amount of files

**Comment by phillipberndt** [comment]
That's possible already, since Glib's file abstraction library Gio support
URLs. Maybe your glib is compiled without http support? Please check if
that's the case, if your glib is by chance *very* old, if the statically
linked binary linked from the repository's readme can load url's for you,
and if other gtk apps are able to handle urls (gedit is a good candidate).

If neither leads you to the answer, please post as much debug info as you
can give me. I'm currently on vacation but will be able to investigate once
I return.

**Comment by anonish** [comment]
alright based on what you wrote, I figured it out, I needed gvfs installed (you may want to add that to dependencies).
I'm using arch linux, and kde (so not a lot of gnome/gtk packages installed) and gvfs was not required by any packages.   it's strange, mirage (a gtk image viewer) worked fine, but pqiv did not, and I installed gvfs and now both work.  geeqie (another gtk based image viewer) still does not load urls, but I think that feature is not supported.  

closing as fixed.

**Comment by phillipberndt** [comment]
Great. Thanks for the info regarding gvfs, good to know, will do.
