### ISSUE TITLE
Memory Leak when displaying animated GIF images

### ISSUE THREAD

**Issue by ntfwc** [phillipberndt/pqiv#87]
Steps to reproduce:
- Open an animated GIF.
`pqiv image.gif`

Expected:
- After the first animation cycle, memory usage stops increasing.

Actual:
- Memory usage continually increases.

Note: Even if pqiv switches to another image, the memory is never released.

pqiv versions tested:
- 2.2 (Ubuntu repository)
- 2.8.3
- master (e416695ac7c7133a92fd3477c1b71a89d623a78d)

System information:
* Operating system: Xubuntu 16.04
* Xorg: Intel modesetting driver (DRI 3)
* 3D: Mesa 12.0.6

**Comment by phillipberndt** [comment]
Thanks for letting me know. I'll investigate once I return from my vacation.

**Comment by phillipberndt** [comment]
I cannot reproduce this. (Memory usage does increase for me as well, but stops increasing once what apparently is an internal cache of either GdkPixbuf, Gdk, Cairo or X11 is saturated, which happens quite fast. Compiling with `-fsanitize=leak` does not show any serious leaks, and none within pqiv's responsibility.) Maybe this depends on the file?! I'm using a Xenial based distribution as well, so our library versions should match.

Regarding the note, pqiv maintains the adjacent images in ram. See `--low-memory`. Did you know this / test that this isn't responsible for what you're observing?

**Comment by ntfwc** [comment]
So, it seems it is only certain GIF images that cause it. Here is a hummingbird GIF that causes it for me:
[https://i.giphy.com/qubH3AqBWTp3q.gif](url)

It takes some time with this one, but I saw it creep up past a GB before I stopped it. I've seen pqiv memory usage go beyond 4GB, so I don't think there is a limit.

Even with `--low-memory`, it still occurs, and switching images still retains the memory. Just to make sure, I did try checking my binary with ldd, and it doesn't seem to be linking against anything but the standard libraries.

I did try compiling it with `-fsanitize=leak`, but it didn't end up printing out anything (I haven't used -fsanitize=leak before, so it's possible I did something wrong).

**Comment by phillipberndt** [comment]
Great, I can reproduce the problem with your gif. Thanks a lot :-)

I think that the problem wasn't actually restricted to animated gifs, but to small images (that required choosing a small font size for the info text due to the resulting window size). It only became noticeable for the gifs because gifs with a high frame rate trigger frequent redraws of the info text. The bug was the following:

I select the font size using trial-and-error upon each redraw of an image. I first choose the largest font size, trace the path that would be taken by writing the text, check if it is within the window bounds, and iterate with smaller font sizes until it is. Now while I free'd the path after eventually using it, I forgot to free the intermediate paths.

For me, the bug is gone with the latest commit in master. Could you verify that it resolves the issue for you as well, please?

**Comment by ntfwc** [comment]
I can confirm that the latest commit eliminates the leak. Excellent work.

**Comment by phillipberndt** [comment]
I've pushed a branch 2.8.4-rc1 with an improved fix (which caches the font size to improve performance). I'll release it as 2.8.4 once I found the time to test it thoroughly. Again, thanks for pointing this out and testing the fix :-)
