### ISSUE TITLE
sort together with lazy-load

### ISSUE THREAD

**Issue by pa-d-v** [phillipberndt/pqiv#93]
pqiv version 2.8.5
The --sort option combined with --lazy-load doesn't show the expected first image by name but an image
somewhere inbetween.

**Comment by phillipberndt** [comment]
This is intended. The idea behind `--lazy-load` is to show the window as soon as the first image is available. This isn't necessarily the one that comes first in order - pqiv cannot tell which comes first until it finished searching for images in the directories given on the command line. To wait until it finished loading, you mustn't use `--lazy-load`.

**Comment by pa-d-v** [comment]
If images in a directory are named e.g. 01.jpg until 74.jpg and I run pqiv -l in that directory I get 35.jpg first, would have expected 01.jpg to be the first image found in the directory like seen with ls. Why is 35.jpg show first?

Perhaps it would be nice to issue a warning on the terminal if both sort an lazy-load are used together: sort not used because of lazy-load

**Comment by phillipberndt** [comment]
Because if you access a directory and ask the OS to give you a list of all files contained in it, this list won't be sorted. You have to read all names, and then you can sort them in a separate step. pqiv internally maintains a list of all files. `--sort´ makes pqiv insert new entries into that list such that it remains ordered, instead of simply appending new files to the end as they come in. `--lazy-load` makes pqiv display the main window as soon as the list contains at least one item. 35.jpg simply happens to be the first file in your directory.

This warning would be misleading. pqiv *does* sort the files. 01.jpg will have index 1, and 74.jpg will have index 74. It just happens to start at the 35th image (which, at the point where the main window is shown, is the first and only one..)

**Comment by pa-d-v** [comment]
I understand now. Still think --sort should be the implicit default then since that is what people expect, and an additional e.g. --no-sort could be used if we would want OS order. The original qiv does that to, probably that caused my confusion.

**Comment by phillipberndt** [comment]
In early 2007, when I created pqiv because [qiv was unmaintained and used the obsolete imlib](https://bugs.gentoo.org/show_bug.cgi?id=166009), qiv would only sort files if explicitly told so. pqiv intentionally behaves this way to maintain compatibility with the original qiv behavior. It's the new qiv maintainers who changed this.

I agree that sorting by default is more sensible, but I won't change this until 3.0, because I don't want to break compatibility.

For now, you can simply create a configuration file with

    [options]
    sort=1

pqiv will then sort by default, and automatically remap `-n` to `--no-sort`.
